// <auto-generated />
namespace PlagiarismCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddNoteColumnToSubmittedAssignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNoteColumnToSubmittedAssignment));
        
        string IMigrationMetadata.Id
        {
            get { return "201812100700024_AddNoteColumnToSubmittedAssignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
